gText_Birch_Welcome:: @ 82C897B
	.string "Greetings! Welcome to the Elara region!\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "Why are you looking in here?”\p"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "You must be a student from Zaurak City\n"
	.string "Hospital. \p"
	.string "I’m one of Elara’s Pokémon Professors.\p"
	.string "$"


gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Why don’t you tell me about yourself?\p"
	.string "$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?\n"
	.string "$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "And what’s your name?"
	.string "$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it’s {PLAYER}{KUN}?$"
	.string "$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Nice to meet you {PLAYER}{KUN}.\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Now, you must be busy with classes\n"
	.string "and exams.\p"
	.string "I hope I’ll see you around.\n"
	.string "Take care and good luck!\p"
	.string "$"
