ZaurakCity_HospitalElevator_EventObjects::
	object_event 1, EVENT_OBJ_GFX_TEALA, 0, 0, 5, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, FALSE, 0, ZaurakCity_HospitalElevator_EventScript_220624, 0

ZaurakCity_HospitalElevator_MapWarps::
	warp_def 1, 5, 3, 127, MAP_NONE
	warp_def 2, 5, 3, 127, MAP_NONE

ZaurakCity_HospitalElevator_MapEvents::
	map_events ZaurakCity_HospitalElevator_EventObjects, ZaurakCity_HospitalElevator_MapWarps, 0x0, 0x0
